[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' https://cdn.jsdelivr.net https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline' 'unsafe-eval';
      script-src-elem 'self' https://cdn.jsdelivr.net https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline' 'unsafe-eval';
      style-src 'self' https://cdn.jsdelivr.net 'unsafe-inline';
      font-src 'self' https://cdn.jsdelivr.net;
      img-src 'self' data: https://www.google-analytics.com;
      connect-src 'self' https://www.google-analytics.com;
      frame-src https://www.google.com https://maps.google.com;
      object-src 'none';
    '''
